### PR TITLE
csv_tree.getCounter()

### PR DESCRIPTION
**Pull request by cclauss**
https://docs.python.org/3.8/library/collections.html#collections.Counter

### CODE REVIEW

**Comment by MartinPacker** [comment]
Will this break the (imminent) merge with the stats branch?

**Comment by cclauss** [comment]
**Merge stats first** and then we will see.  This should land smoothly because it is self contained (not hooked up).

**Comment by MartinPacker** [comment]
OK. About to do that.

**Comment by MartinPacker** [comment]
Merged and checks ran fine. Now to merge yours and see what happens.

**Pull request merged**
